### ISSUE TITLE
sendText - Generic error step 2 tutorial

### ISSUE THREAD

**Issue by TGw44** [tawn33y/whatsapp-cloud-api#33]
Hello, i just followed the tutorial steps and i have this response after step 2

{
  error: {
    message: '(#131000) Generic error',
    type: 'OAuthException',
    code: 131000,
    error_data: { messaging_product: 'whatsapp', details: 'Generic error' },
    error_subcode: 2494002,
    fbtrace_id: 'AC1dtC9ImEGwkBiss2Xt0mA'
  }
}

I could make it work using Postman.

**Comment by tawn33y** [comment]
Hi, can you share a snippet the code you're using? (you can commit auth tokens, phone numbers, etc).

**Comment by TGw44** [comment]
const { createBot } = require('whatsapp-cloud-api');

(async () => {
  try {
    // replace the values below from the values you copied above
    const from = 'IDPROVIDEDBYFB';
    const token = 'TOKENPROVIDEDBYFB';
    const to = 'My test phone number'; // your phone number without the leading '+'
    const webhookVerifyToken = ''; // use a random value, e.g. 'bju#hfre@iu!e87328eiekjnfw'

    const bot = createBot(from, token);

    const result = await bot.sendText(to, 'Hello world');

    // Start express server to listen for incoming messages
    await bot.startExpressServer({
      webhookVerifyToken,
    });

    // Listen to ALL incoming messages
    bot.on('message', async (msg) => {
      console.log(msg);

      if (msg.type === 'text') {
        await bot.sendText(msg.from, 'Received your text message!');
      } else if (msg.type === 'image') {
        await bot.sendText(msg.from, 'Received your image!');
      }
    });
  } catch (err) {
    console.log(err);
  }
})();







file package.json

{
  "name": "hello-whatsapp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
   "start": "node ./src/index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "whatsapp-cloud-api": "^0.2.6"
  }
}




npm start

{
  error: {
    message: '(#131000) Generic error',
    type: 'OAuthException',
    code: 131000,
    error_data: { messaging_product: 'whatsapp', details: 'Generic error' },
    error_subcode: 2494002,
    fbtrace_id: 'AVyE_ZkI13EVqXDwGUOPAyQ'
  }
}

**Comment by j05u3** [comment]
Hi @TGw44, I think I had an error very similar to yours, I fixed it by doing this https://stackoverflow.com/a/73230897/2469583

**Comment by tawn33y** [comment]
Thanks for sharing, @j05u3!

@TGw44, let us know if this works

**Comment by TGw44** [comment]
> Hi @TGw44, I think I had an error very similar to yours, I fixed it by doing this https://stackoverflow.com/a/73230897/2469583

Thanks @j05u3, i tried but i still have the problem.

As i said, if i do the post from postman, the text is sent correctly with the same credentials and token.

**Comment by TGw44** [comment]
Sorry for making you lose time. 

It was a problem with the phone number.

const to = 'My test phone number'; // your phone number without the leading '+'



Thanks!
